// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/parts/BaseButton.vue')['default']
    LoadSpinner: typeof import('./src/components/parts/LoadSpinner.vue')['default']
    ModalBack: typeof import('./src/components/parts/ModalBack.vue')['default']
    ModalBase: typeof import('./src/components/modules/ModalBase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/modules/SearchBox.vue')['default']
    SelectInput: typeof import('./src/components/parts/SelectInput.vue')['default']
    SvgIcon: typeof import('./src/components/parts/SvgIcon.vue')['default']
    TheFooter: typeof import('./src/components/modules/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/modules/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/modules/TheSidebar.vue')['default']
    ToggleSwitch: typeof import('./src/components/parts/ToggleSwitch.vue')['default']
    Tooltip: typeof import('./src/components/parts/Tooltip.vue')['default']
    TransparentBack: typeof import('./src/components/parts/TransparentBack.vue')['default']
  }
}
